resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/carlyledavis/concourse.git
    branch: master

jobs:
- name: compile-source
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/config/build.yml
  - task: unit-test
    file: source-code/config/unit-test.yml
